server:
  port: 9002
spring:
  application:
    name: hp-dgf-tool
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dgf
    username: rajat
    password: 123456789
  jpa:
    hibernate.ddl-auto: none
    database: mysql
  security:
    user:
      name: admin
      password: hp