server:
  port: 9002
spring:
  application:
    name: dgf-tool
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dgf_sandbox?serverTimezone=UTC
    username: root
    password:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate.ddl-auto: none
    database: mysql
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 20MB
file:
  upload-dir: uploads
